# Generated by Django 5.1.7 on 2025-06-05 19:33

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PacientexServicio',
            fields=[
                ('clave', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_salida', models.DateTimeField()),
                ('fecha_llegada', models.DateTimeField()),
                ('fecha_retorno', models.DateTimeField()),
                ('apellido_paterno', models.CharField(max_length=50)),
                ('apellido_materno', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=50)),
                ('edad', models.IntegerField()),
                ('sexo', models.CharField(max_length=1)),
                ('estado_civil', models.CharField(max_length=1)),
                ('telefono', models.CharField(max_length=20)),
                ('estatura', models.DecimalField(decimal_places=2, max_digits=5)),
                ('complexion', models.CharField(max_length=1)),
                ('tez', models.CharField(max_length=1)),
                ('pelo', models.CharField(max_length=1)),
                ('ropa', models.CharField(max_length=100)),
                ('placa_vehiculo', models.CharField(max_length=10)),
                ('color_vehiculo', models.CharField(max_length=1)),
                ('fecha_ultima_comida', models.DateTimeField()),
                ('fallecio', models.BooleanField(default=False)),
                ('tiene_acompanante', models.BooleanField(default=False)),
                ('nombre_acompanante', models.CharField(max_length=100)),
                ('edad_acompanante', models.IntegerField()),
                ('domicilio_acompanante', models.CharField(max_length=150)),
                ('parentesco_acompanante', models.CharField(max_length=2)),
                ('sexo_acompanante', models.CharField(max_length=1)),
                ('entregan_pertenencias', models.BooleanField(default=False)),
                ('descripcion_pertenencias', models.TextField()),
                ('nombre_recibe', models.CharField(max_length=100)),
                ('cargo_recibe', models.CharField(max_length=100)),
                ('libera_responsabilidad', models.BooleanField(default=False)),
                ('fecha_liberacion_respon', models.DateTimeField(default=False)),
                ('firmo_liberacion', models.BooleanField(default=False)),
                ('niega_firmar', models.BooleanField(default=False)),
                ('nombre_respon_hospital', models.CharField(max_length=100)),
                ('nombre_agente', models.CharField(max_length=100)),
                ('numero_agente', models.CharField(max_length=10)),
                ('nivel_concienciaa', models.CharField(max_length=1)),
                ('piel', models.CharField(max_length=1)),
                ('antecedente', models.CharField(max_length=255)),
                ('sintoma', models.TextField()),
                ('pulso_diagnostico', models.CharField(max_length=1)),
                ('respiracion_diagnostico', models.CharField(max_length=1)),
                ('pupilas', models.CharField(max_length=1)),
                ('hemorragia', models.CharField(max_length=1)),
                ('dolor', models.CharField(max_length=1)),
                ('pulso', models.CharField(max_length=10)),
                ('respiracion', models.CharField(max_length=10)),
                ('presion_inicial', models.CharField(max_length=10)),
                ('presion_posterior', models.CharField(max_length=10)),
                ('destroxtix', models.CharField(max_length=10)),
                ('oximetria', models.CharField(max_length=10)),
                ('temperatura', models.CharField(max_length=10)),
                ('apertura_ojos_glasgow', models.CharField(max_length=1)),
                ('respuesta_verbal_glasgow', models.CharField(max_length=1)),
                ('respuesta_motora_glasgow', models.CharField(max_length=1)),
                ('edad_tipo', models.CharField(max_length=1)),
                ('domicilio_numero', models.CharField(max_length=10)),
                ('ambulancia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.ambulancias')),
                ('base', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.bases')),
                ('colonia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.colonia')),
                ('domicilio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.calle')),
                ('empleado_recibe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recibe_paciente', to='catalogos.paramedicos')),
                ('enfermedad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.enfermedad')),
                ('hospital', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.hospitales')),
                ('marca_vehiculo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.marcavehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='MedIngeridoxPaciente',
            fields=[
                ('clave', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('medicamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.medicamento')),
                ('paciente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='procesos.pacientexservicio')),
            ],
        ),
        migrations.CreateModel(
            name='MedAdministradoxPaciente',
            fields=[
                ('clave', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('costo', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('medicamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.medicamento')),
                ('paciente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='procesos.pacientexservicio')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialxPaciente',
            fields=[
                ('clave', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('costo', models.DecimalField(decimal_places=2, max_digits=18)),
                ('material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.material')),
                ('paciente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='procesos.pacientexservicio')),
            ],
        ),
        migrations.CreateModel(
            name='LesionxPaciente',
            fields=[
                ('clave', models.AutoField(primary_key=True, serialize=False)),
                ('lesion', models.CharField(max_length=100)),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('paciente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='procesos.pacientexservicio')),
            ],
        ),
        migrations.CreateModel(
            name='ImpactoxVehiculo',
            fields=[
                ('clave', models.AutoField(primary_key=True, serialize=False)),
                ('impacto', models.CharField(max_length=100)),
                ('paciente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='procesos.pacientexservicio')),
            ],
        ),
        migrations.CreateModel(
            name='EquipoxPaciente',
            fields=[
                ('clave', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('equipo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.equipo')),
                ('paciente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='procesos.pacientexservicio')),
            ],
        ),
        migrations.CreateModel(
            name='EmbarazoxPaciente',
            fields=[
                ('secuencia', models.IntegerField(primary_key=True, serialize=False)),
                ('numero_gestaciones', models.IntegerField()),
                ('numero_partos', models.IntegerField()),
                ('numero_cesareas', models.IntegerField()),
                ('numero_abortos', models.IntegerField()),
                ('utlima_menstruacion', models.DateTimeField()),
                ('edad_gestacional', models.IntegerField()),
                ('presenta_sangrado', models.BooleanField(default=False)),
                ('inicio_contracciones', models.DateTimeField()),
                ('bolsa_rota', models.BooleanField(default=False)),
                ('atencion_medica_embarazo', models.BooleanField(default=False)),
                ('nota', models.TextField()),
                ('paciente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='procesos.pacientexservicio')),
            ],
        ),
        migrations.CreateModel(
            name='AlergiaxPaciente',
            fields=[
                ('clave', models.AutoField(primary_key=True, serialize=False)),
                ('alergia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.alergia')),
                ('paciente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='procesos.pacientexservicio')),
            ],
        ),
        migrations.CreateModel(
            name='ProcedimientoxPaciente',
            fields=[
                ('clave', models.AutoField(primary_key=True, serialize=False)),
                ('paciente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='procesos.pacientexservicio')),
                ('procedimiento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.procedimiento')),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('clave', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(default=datetime.datetime.now)),
                ('descripcion_evento', models.TextField()),
                ('nombre_persona_reporta', models.CharField(max_length=100)),
                ('telefono_persona_reporta', models.CharField(max_length=20)),
                ('sexo_persona_reporta', models.CharField(max_length=1)),
                ('edad_persona_reporta', models.IntegerField()),
                ('estatus', models.CharField(max_length=1)),
                ('calle_entre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calle_entre', to='catalogos.calle')),
                ('colonia_emergencia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.colonia')),
                ('direccion_emergencia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.calle')),
                ('tipo_servicio_realizado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicios_realizados', to='catalogos.tiposservicio')),
                ('tipo_servicio_reporta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicios_reportados', to='catalogos.tiposservicio')),
            ],
        ),
        migrations.CreateModel(
            name='PartexServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parte', models.TextField()),
                ('servicio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='procesos.servicio')),
            ],
        ),
        migrations.CreateModel(
            name='ParamedicoxPaciente',
            fields=[
                ('clave', models.AutoField(primary_key=True, serialize=False)),
                ('paciente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='procesos.pacientexservicio')),
                ('paramedico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.paramedicos')),
                ('servicio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='procesos.servicio')),
            ],
        ),
        migrations.AddField(
            model_name='pacientexservicio',
            name='servicio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pacientes', to='procesos.servicio'),
        ),
        migrations.CreateModel(
            name='TestigoxPaciente',
            fields=[
                ('clave', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('domicilio', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('paciente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='procesos.pacientexservicio')),
            ],
        ),
        migrations.CreateModel(
            name='UnidadxServicio',
            fields=[
                ('clave', models.AutoField(primary_key=True, serialize=False)),
                ('numero_unidad', models.CharField(max_length=20)),
                ('agente_nombre', models.CharField(max_length=100)),
                ('servicio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='procesos.servicio')),
                ('unidad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.tipounidad')),
            ],
        ),
    ]
