# Generated by Django 5.1.7 on 2025-04-02 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0003_alter_alergia_descripcion_alter_ambulancias_base_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('clave', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('descripcion_evento', models.TextField()),
                ('nombre_persona_reporta', models.CharField(max_length=100)),
                ('telefono_persona_reporta', models.CharField(max_length=20)),
                ('sexo_persona_reporta', models.CharField(max_length=1)),
                ('estatus', models.CharField(choices=[('P', 'EN PROCESO'), ('T', 'TERMINADO'), ('C', 'CANCELADO')], max_length=1)),
                ('calle_entre', models.CharField(max_length=255)),
                ('colonia_emergencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.colonia')),
                ('direccion_emergencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.calle')),
                ('tipo_servicio_realizado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios_realizados', to='catalogos.tiposservicio')),
                ('tipo_servicio_reporta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios_reportados', to='catalogos.tiposservicio')),
            ],
        ),
    ]
