# Generated by Django 5.1.7 on 2025-04-02 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='edad_persona_reporta',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
