# Generated by Django 5.1.7 on 2025-04-02 19:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesos', '0002_servicio_edad_persona_reporta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
