# Generated by Django 5.1.7 on 2025-06-06 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesos', '0002_alter_pacientexservicio_nombre_recibe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacientexservicio',
            name='cargo_recibe',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
