# Generated by Django 5.1.7 on 2025-06-06 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesos', '0003_alter_pacientexservicio_cargo_recibe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacientexservicio',
            name='oximetria',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
