# Generated by Django 5.1.7 on 2025-04-03 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0003_alter_alergia_descripcion_alter_ambulancias_base_and_more'),
        ('procesos', '0003_alter_servicio_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='estatus',
            field=models.CharField(max_length=1),
        ),
        migrations.CreateModel(
            name='ParamedicoxPaciente',
            fields=[
                ('clave', models.IntegerField(primary_key=True, serialize=False)),
                ('paciente', models.CharField(max_length=100)),
                ('paramedico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.paramedicos')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='procesos.servicio')),
            ],
        ),
        migrations.CreateModel(
            name='UnidadxServicio',
            fields=[
                ('clave', models.IntegerField(primary_key=True, serialize=False)),
                ('numero_unidad', models.CharField(max_length=20)),
                ('agente_nombre', models.CharField(max_length=100)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='procesos.servicio')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.tipounidad')),
            ],
        ),
    ]
