# Generated by Django 5.1.7 on 2025-06-06 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesos', '0004_alter_pacientexservicio_oximetria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacientexservicio',
            name='temperatura',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
