# Generated by Django 5.1.7 on 2025-04-09 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesos', '0005_alter_paramedicoxpaciente_paramedico_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacientexservicio',
            name='fecha_ultima_comida',
            field=models.DateTimeField(),
        ),
    ]
