# Generated by Django 5.1.7 on 2025-06-06 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesos', '0006_alter_pacientexservicio_domicilio_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacientexservicio',
            name='apertura_ojos_glasgow',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='pacientexservicio',
            name='color_vehiculo',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='pacientexservicio',
            name='complexion',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='pacientexservicio',
            name='dolor',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='pacientexservicio',
            name='edad_tipo',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='pacientexservicio',
            name='estado_civil',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='pacientexservicio',
            name='hemorragia',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='pacientexservicio',
            name='nivel_concienciaa',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='pacientexservicio',
            name='pelo',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='pacientexservicio',
            name='piel',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='pacientexservicio',
            name='pulso_diagnostico',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='pacientexservicio',
            name='pupilas',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='pacientexservicio',
            name='respiracion_diagnostico',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='pacientexservicio',
            name='respuesta_motora_glasgow',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='pacientexservicio',
            name='respuesta_verbal_glasgow',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='pacientexservicio',
            name='sexo',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='pacientexservicio',
            name='sexo_acompanante',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='pacientexservicio',
            name='tez',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='estatus',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='sexo_persona_reporta',
            field=models.CharField(max_length=10),
        ),
    ]
