# Generated by Django 5.1.7 on 2025-04-09 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesos', '0006_alter_pacientexservicio_fecha_ultima_comida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacientexservicio',
            name='fecha_liberacion_respon',
            field=models.DateTimeField(),
        ),
    ]
