# Generated by Django 5.1.7 on 2025-06-06 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesos', '0007_alter_pacientexservicio_apertura_ojos_glasgow_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacientexservicio',
            name='edad_tipo',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
