# Generated by Django 5.1.7 on 2025-04-16 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesos', '0007_alter_pacientexservicio_fecha_liberacion_respon'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacientexservicio',
            name='oximetria',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pacientexservicio',
            name='temperatura',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
