# Generated by Django 5.1.7 on 2025-06-11 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesos', '0008_alter_pacientexservicio_edad_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medadministradoxpaciente',
            name='costo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, null=True),
        ),
    ]
