# Generated by Django 5.1.7 on 2025-04-23 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesos', '0008_pacientexservicio_oximetria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paramedicoxpaciente',
            name='paciente',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
