# Generated by Django 5.1.7 on 2025-04-23 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesos', '0009_alter_paramedicoxpaciente_paciente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paramedicoxpaciente',
            name='clave',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
