# Generated by Django 5.1.7 on 2025-06-16 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesos', '0009_alter_medadministradoxpaciente_costo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testigoxpaciente',
            name='domicilio',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='testigoxpaciente',
            name='nombre',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='testigoxpaciente',
            name='telefono',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
