# Generated by Django 5.1.7 on 2025-04-23 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesos', '0010_alter_paramedicoxpaciente_clave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidadxservicio',
            name='clave',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
