# Generated by Django 5.1.7 on 2025-06-17 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0006_alter_paramedicos_contrasena'),
        ('procesos', '0010_alter_testigoxpaciente_domicilio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Combustible',
            fields=[
                ('clave', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField()),
                ('turno', models.IntegerField()),
                ('litros', models.DecimalField(decimal_places=2, max_digits=7)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=7)),
                ('remision', models.CharField(max_length=20, null=True)),
                ('factura', models.CharField(max_length=20, null=True)),
                ('tipo', models.CharField(max_length=1, null=True)),
                ('ambulancia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.ambulancias')),
                ('encargado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encargado_combustible', to='catalogos.paramedicos')),
                ('supervisor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.paramedicos')),
            ],
        ),
    ]
