# Generated by Django 5.1.7 on 2025-06-17 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesos', '0011_combustible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='edad_persona_reporta',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='nombre_persona_reporta',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='sexo_persona_reporta',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='telefono_persona_reporta',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
