# Generated by Django 5.1.7 on 2025-04-25 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesos', '0011_alter_unidadxservicio_clave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacientexservicio',
            name='entregan_pertenencias',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pacientexservicio',
            name='fallecio',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pacientexservicio',
            name='fecha_liberacion_respon',
            field=models.DateTimeField(default=False),
        ),
        migrations.AlterField(
            model_name='pacientexservicio',
            name='firmo_liberacion',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pacientexservicio',
            name='libera_responsabilidad',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pacientexservicio',
            name='niega_firmar',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pacientexservicio',
            name='tiene_acompanante',
            field=models.BooleanField(default=False),
        ),
    ]
