# Generated by Django 5.1.7 on 2025-06-18 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesos', '0012_alter_servicio_edad_persona_reporta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacientexservicio',
            name='placa_vehiculo',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
