# Generated by Django 5.1.7 on 2025-04-28 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0004_alter_calle_colonia_calle_and_more'),
        ('procesos', '0012_alter_pacientexservicio_entregan_pertenencias_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlergiaxPaciente',
            fields=[
                ('clave', models.IntegerField(primary_key=True, serialize=False)),
                ('alergia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.alergia')),
                ('paciente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='procesos.pacientexservicio')),
            ],
        ),
        migrations.CreateModel(
            name='EquipoxPaciente',
            fields=[
                ('clave', models.IntegerField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('equipo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.equipo')),
                ('paciente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='procesos.pacientexservicio')),
            ],
        ),
        migrations.CreateModel(
            name='ImpactoxVehiculo',
            fields=[
                ('clave', models.IntegerField(primary_key=True, serialize=False)),
                ('impacto', models.CharField(max_length=100)),
                ('paciente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='procesos.pacientexservicio')),
            ],
        ),
        migrations.CreateModel(
            name='LesionxPaciente',
            fields=[
                ('clave', models.IntegerField(primary_key=True, serialize=False)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=5)),
                ('lesion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.material')),
                ('paciente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='procesos.pacientexservicio')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialxPaciente',
            fields=[
                ('clave', models.IntegerField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('costo', models.DecimalField(decimal_places=2, max_digits=18)),
                ('alergia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.material')),
                ('paciente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='procesos.pacientexservicio')),
            ],
        ),
        migrations.CreateModel(
            name='MedAdministradoxPaciente',
            fields=[
                ('clave', models.IntegerField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('costo', models.DecimalField(decimal_places=2, max_digits=18)),
                ('medicamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.medicamento')),
                ('paciente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='procesos.pacientexservicio')),
            ],
        ),
        migrations.CreateModel(
            name='MedIngeridoxPaciente',
            fields=[
                ('clave', models.IntegerField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('medicamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.medicamento')),
                ('paciente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='procesos.pacientexservicio')),
            ],
        ),
        migrations.CreateModel(
            name='ProcedimientoxPaciente',
            fields=[
                ('clave', models.IntegerField(primary_key=True, serialize=False)),
                ('paciente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='procesos.pacientexservicio')),
                ('procedimiento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.procedimiento')),
            ],
        ),
    ]
