# Generated by Django 5.1.7 on 2025-06-18 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesos', '0013_alter_pacientexservicio_placa_vehiculo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacientexservicio',
            name='color_vehiculo',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
