# Generated by Django 5.1.7 on 2025-04-28 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesos', '0013_alergiaxpaciente_equipoxpaciente_impactoxvehiculo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesionxpaciente',
            name='lesion',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='procedimientoxpaciente',
            name='clave',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
