# Generated by Django 5.1.7 on 2025-04-28 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesos', '0014_alter_lesionxpaciente_lesion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alergiaxpaciente',
            name='clave',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='equipoxpaciente',
            name='clave',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='impactoxvehiculo',
            name='clave',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lesionxpaciente',
            name='clave',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='materialxpaciente',
            name='clave',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='medadministradoxpaciente',
            name='clave',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='medingeridoxpaciente',
            name='clave',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
