# Generated by Django 5.1.7 on 2025-06-18 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesos', '0014_alter_pacientexservicio_color_vehiculo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacientexservicio',
            name='antecedente',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pacientexservicio',
            name='apertura_ojos_glasgow',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='pacientexservicio',
            name='destroxtix',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='pacientexservicio',
            name='dolor',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='pacientexservicio',
            name='domicilio_numero',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='pacientexservicio',
            name='edad_tipo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='pacientexservicio',
            name='fecha_liberacion_respon',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pacientexservicio',
            name='hemorragia',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='pacientexservicio',
            name='nivel_concienciaa',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='pacientexservicio',
            name='nombre_agente',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pacientexservicio',
            name='nombre_respon_hospital',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pacientexservicio',
            name='numero_agente',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='pacientexservicio',
            name='oximetria',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='pacientexservicio',
            name='piel',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='pacientexservicio',
            name='presion_inicial',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='pacientexservicio',
            name='presion_posterior',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='pacientexservicio',
            name='pulso',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='pacientexservicio',
            name='pulso_diagnostico',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='pacientexservicio',
            name='pupilas',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='pacientexservicio',
            name='respiracion',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='pacientexservicio',
            name='respiracion_diagnostico',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='pacientexservicio',
            name='respuesta_motora_glasgow',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='pacientexservicio',
            name='respuesta_verbal_glasgow',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='pacientexservicio',
            name='sintoma',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pacientexservicio',
            name='temperatura',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
