# Generated by Django 5.1.7 on 2025-04-28 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procesos', '0015_alter_alergiaxpaciente_clave_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='materialxpaciente',
            old_name='alergia',
            new_name='material',
        ),
    ]
