# Generated by Django 5.1.7 on 2025-06-18 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesos', '0015_alter_pacientexservicio_antecedente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacientexservicio',
            name='domicilio_numero',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
