# Generated by Django 5.1.7 on 2025-04-30 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesos', '0016_rename_alergia_materialxpaciente_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medadministradoxpaciente',
            name='costo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
    ]
