# Generated by Django 5.1.7 on 2025-05-14 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesos', '0017_alter_medadministradoxpaciente_costo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesionxpaciente',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='pacientexservicio',
            name='color_vehiculo',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='pacientexservicio',
            name='servicio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pacientes', to='procesos.servicio'),
        ),
        migrations.CreateModel(
            name='EmbarazoxPaciente',
            fields=[
                ('secuencia', models.AutoField(primary_key=True, serialize=False)),
                ('numero_gestaciones', models.IntegerField()),
                ('numero_partos', models.IntegerField()),
                ('numero_cesareas', models.IntegerField()),
                ('numero_abortos', models.IntegerField()),
                ('utlima_menstruacion', models.DateTimeField()),
                ('edad_gestacional', models.IntegerField()),
                ('presenta_sangrado', models.BooleanField(default=False)),
                ('inicio_contracciones', models.DateTimeField()),
                ('bolsa_rota', models.BooleanField(default=False)),
                ('atencion_medica_embarazo', models.BooleanField(default=False)),
                ('nota', models.TextField()),
                ('paciente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='procesos.pacientexservicio')),
            ],
        ),
        migrations.CreateModel(
            name='PartexServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parte', models.TextField()),
                ('servicio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='procesos.servicio')),
            ],
        ),
        migrations.CreateModel(
            name='TestigoxPaciente',
            fields=[
                ('clave', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('domicilio', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('paciente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='procesos.pacientexservicio')),
            ],
        ),
    ]
