# Generated by Django 5.1.7 on 2025-06-18 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesos', '0017_alter_pacientexservicio_domicilio_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacientexservicio',
            name='apellido_materno',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pacientexservicio',
            name='apellido_paterno',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pacientexservicio',
            name='descripcion_pertenencias',
            field=models.TextField(blank=True, null=True),
        ),
    ]
