# Generated by Django 5.1.7 on 2025-05-23 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0009_alter_calle_colonia_id'),
        ('procesos', '0018_alter_lesionxpaciente_valor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='calle_entre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calle_entre', to='catalogos.calle'),
        ),
    ]
