# Generated by Django 5.1.7 on 2025-06-18 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesos', '0018_alter_pacientexservicio_apellido_materno_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuemaduraxPaciente',
            fields=[
                ('clave', models.AutoField(primary_key=True, serialize=False)),
                ('quemadura', models.CharField(max_length=100)),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('paciente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='procesos.pacientexservicio')),
            ],
        ),
    ]
