# Generated by Django 5.1.7 on 2025-05-26 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesos', '0019_alter_servicio_calle_entre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacientexservicio',
            name='sintoma',
            field=models.TextField(max_length=255),
        ),
    ]
