# Generated by Django 5.1.7 on 2025-06-19 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0006_alter_paramedicos_contrasena'),
        ('procesos', '0019_quemaduraxpaciente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reloj',
            fields=[
                ('clave', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField()),
                ('estatus', models.CharField(max_length=1)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('paramedico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.paramedicos')),
            ],
        ),
    ]
