# Generated by Django 5.1.7 on 2025-08-12 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0009_alter_paramedicos_permisos'),
        ('procesos', '0020_reloj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacientexservicio',
            name='domicilio_acompanante',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='pacientexservicio',
            name='edad_acompanante',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pacientexservicio',
            name='fecha_ultima_comida',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pacientexservicio',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.hospitales'),
        ),
        migrations.AlterField(
            model_name='pacientexservicio',
            name='marca_vehiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.marcavehiculo'),
        ),
        migrations.AlterField(
            model_name='pacientexservicio',
            name='nombre_acompanante',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pacientexservicio',
            name='placa_vehiculo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
