# Generated by Django 5.1.7 on 2025-05-26 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesos', '0020_alter_pacientexservicio_sintoma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacientexservicio',
            name='descripcion_pertenencias',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='pacientexservicio',
            name='sintoma',
            field=models.TextField(),
        ),
    ]
