# Generated by Django 5.1.7 on 2025-08-12 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0009_alter_paramedicos_permisos'),
        ('procesos', '0021_alter_pacientexservicio_domicilio_acompanante_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacientexservicio',
            name='cargo_recibe',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pacientexservicio',
            name='empleado_recibe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recibe_paciente', to='catalogos.paramedicos'),
        ),
        migrations.AlterField(
            model_name='pacientexservicio',
            name='nombre_recibe',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pacientexservicio',
            name='parentesco_acompanante',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='pacientexservicio',
            name='sexo_acompanante',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
