# Generated by Django 5.1.7 on 2025-05-26 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0009_alter_calle_colonia_id'),
        ('procesos', '0021_alter_pacientexservicio_descripcion_pertenencias_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacientexservicio',
            name='cargo_recibe',
            field=models.CharField(default='Operador', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pacientexservicio',
            name='empleado_recibe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recibe_paciente', to='catalogos.paramedicos'),
        ),
        migrations.AddField(
            model_name='pacientexservicio',
            name='nombre_recibe',
            field=models.CharField(default='Hector Uribe', max_length=100),
            preserve_default=False,
        ),
    ]
