# Generated by Django 5.1.7 on 2025-10-06 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesos', '0022_alter_pacientexservicio_cargo_recibe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacientexservicio',
            name='antecedente',
            field=models.CharField(blank=True, null=True),
        ),
    ]
