# Generated by Django 5.1.7 on 2025-05-27 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesos', '0022_pacientexservicio_cargo_recibe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paramedicoxpaciente',
            name='paciente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='procesos.pacientexservicio'),
        ),
    ]
