# Generated by Django 5.1.7 on 2025-10-06 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesos', '0023_alter_pacientexservicio_antecedente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='embarazoxpaciente',
            name='edad_gestacional',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='embarazoxpaciente',
            name='inicio_contracciones',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='embarazoxpaciente',
            name='nota',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='embarazoxpaciente',
            name='numero_abortos',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='embarazoxpaciente',
            name='numero_cesareas',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='embarazoxpaciente',
            name='numero_gestaciones',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='embarazoxpaciente',
            name='numero_partos',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='embarazoxpaciente',
            name='utlima_menstruacion',
            field=models.DateTimeField(blank=True),
        ),
    ]
