# Generated by Django 5.1.7 on 2025-05-27 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesos', '0023_alter_paramedicoxpaciente_paciente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='embarazoxpaciente',
            name='secuencia',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
