# Generated by Django 5.1.7 on 2025-10-06 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0009_alter_paramedicos_permisos'),
        ('procesos', '0024_alter_embarazoxpaciente_edad_gestacional_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacientexservicio',
            name='hospital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.hospitales'),
        ),
    ]
