# Generated by Django 5.1.7 on 2025-10-06 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesos', '0025_alter_pacientexservicio_hospital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacientexservicio',
            name='fecha_ultima_comida',
            field=models.DateTimeField(default='2025-01-01'),
            preserve_default=False,
        ),
    ]
