# Generated by Django 5.1.7 on 2025-10-07 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesos', '0026_alter_pacientexservicio_fecha_ultima_comida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacientexservicio',
            name='edad',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pacientexservicio',
            name='estatura',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
