# Generated by Django 5.1.7 on 2025-10-07 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesos', '0027_alter_pacientexservicio_edad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacientexservicio',
            name='color_vehiculo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='pacientexservicio',
            name='domicilio_numero',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='pacientexservicio',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
