# Generated by Django 5.1.7 on 2025-10-07 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesos', '0028_alter_pacientexservicio_color_vehiculo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacientexservicio',
            name='domicilio_numero',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
