# Generated by Django 5.1.7 on 2025-10-07 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesos', '0029_alter_pacientexservicio_domicilio_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacientexservicio',
            name='domicilio_numero',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
