# Generated by Django 5.1.7 on 2025-10-07 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesos', '0030_alter_pacientexservicio_domicilio_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='testigoxpaciente',
            name='parentesco',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
