# Generated by Django 5.1.7 on 2025-10-09 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesos', '0031_testigoxpaciente_parentesco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='clave',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
