# Generated by Django 5.1.7 on 2025-10-09 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesos', '0032_alter_servicio_clave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacientexservicio',
            name='clave',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
