# Generated by Django 5.1.7 on 2025-10-13 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesos', '0033_alter_pacientexservicio_clave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partexservico',
            name='parte',
            field=models.TextField(blank=True, null=True),
        ),
    ]
