# Generated by Django 6.0.1 on 2026-01-29 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesos', '0034_alter_partexservico_parte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacientexservicio',
            name='estatura',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=8, null=True),
        ),
    ]
