# Generated by Django 6.0.1 on 2026-03-17 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesos', '0035_alter_pacientexservicio_estatura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='embarazoxpaciente',
            name='secuencia',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
