from django.urls import path
from .views import *

urlpatterns = [
    path('reportes/', cargar_reportes, name='cargar_reportes'),
    path('reportes/servicios/', reporte_servicios, name='reporte_servicios'),
    path('reportes/serviciosambulancias/', reporte_servicios_x_ambulancia, name='reporte_servicios_x_ambulancia'),
    path('reporte/serviciosambulancias/pdf/', imprimir_reporte_ambulancia_pdf, name='imprimir_reporte_ambulancia_pdf'),
    path('reportes/pacientesxbase/', reporte_servicios_x_tipo, name='reporte_servicios_x_tipo'),
    path('reportes/pacientesxbase/pdf', imprimir_reporte_tipo_servicio_pdf, name='imprimir_reporte_tipo_servicio_pdf'),
    path('reportes/serviciosconteo/', resumen_tipo_servicio, name='resumen_tipo_servicio'),
    path('reportes/serviciosconteo/pdf', imprimir_resumen_tipo_servicio_pdf, name='imprimir_resumen_tipo_servicio_pdf'),
    path('reportes/serviciossobresalientes/', reporte_sobresalientes, name='reporte_sobresalientes'),
    path('reportes/serviciossobresalientes/pdf', imprimir_reporte_sobresalientes_pdf, name='imprimir_reporte_sobresalientes_pdf'),
    path('reportes/serviciosparteinformativo/', reporte_parte_informativo, name='reporte_parte_informativo'),
    path('reportes/serviciosparteinformativo/pdf', reporte_parte_informativo_pdf, name='reporte_parte_informativo_pdf'),
    path('reportes/serviciosparamedico/', reporte_paramedico_base, name='reporte_paramedico_base'),
    path('reportes/serviciosparamedico/pdf', reporte_paramedico_base_pdf, name='reporte_paramedico_base_pdf'),
    path('reportes/serviciosmateriales/', reporte_materiales, name='reporte_materiales'),
    path('reportes/serviciosmateriales/pdf', reporte_materiales_pdf, name='reporte_materiales_pdf'),
    path('reportes/serviciosequipo/', reporte_equipos, name='reporte_equipos'),
    path('reportes/serviciosequipo/pdf', reporte_equipos_pdf, name='reporte_equipos_pdf'),
    path('reportes/serviciospacientesxsexo/', reporte_pacientes_por_sexo, name='reporte_pacientes_por_sexo'),
    path('reportes/serviciospacientesxsexo/pdf', reporte_pacientes_por_sexo_pdf, name='reporte_pacientes_por_sexo_pdf'),
    path('reportes/serviciosenfermedaddesgrupo/', reporte_enfermedades_por_grupo, name='reporte_enfermedades_por_grupo'),
    path('reportes/serviciosenfermedaddesgrupo/pdf', reporte_enfermedades_por_grupo_pdf, name='reporte_enfermedades_por_grupo_pdf'),
    path('reportes/serviciosmaterialespaciente/', reporte_materiales_pacientes, name='reporte_materiales_pacientes'),
    path('reportes/serviciosmaterialespaciente/pdf', reporte_materiales_pacientes_pdf, name='reporte_materiales_pacientes_pdf'),
    path('reportes/serviciosmedicamentospaciente/', reporte_medicamentos_pacientes, name='reporte_medicamentos_pacientes'),
    path('reportes/serviciosmedicamentospaciente/pdf', reporte_medicamentos_pacientes_pdf, name='reporte_medicamentos_pacientes_pdf'),
]