# Generated by Django 5.1.7 on 2025-03-26 19:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alergia',
            fields=[
                ('clave', models.IntegerField(primary_key=1, serialize=False)),
                ('descripcion', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ambulancias',
            fields=[
                ('clave', models.TextField(max_length=5, primary_key=1, serialize=False)),
                ('descripcion', models.TextField(max_length=50)),
                ('estado', models.TextField(max_length=1)),
                ('base', models.TextField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Bases',
            fields=[
                ('clave', models.TextField(max_length=20, primary_key=1, serialize=False)),
                ('estacion', models.TextField(max_length=50)),
                ('ubicacion', models.TextField(max_length=100)),
                ('rojo', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(255)])),
                ('azul', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(255)])),
                ('verde', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(255)])),
            ],
        ),
        migrations.CreateModel(
            name='Calle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Colonia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colonia', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('clave', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
                ('unidad', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='GrupoEnfermedad',
            fields=[
                ('clave', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='GrupoServicio',
            fields=[
                ('clave', models.IntegerField(primary_key=1, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Hospitales',
            fields=[
                ('clave', models.IntegerField(primary_key=1, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('ubicacion', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='MarcaVehiculo',
            fields=[
                ('clave', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('clave', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
                ('unidad', models.CharField(max_length=10)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=18)),
            ],
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('clave', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
                ('unidad', models.CharField(max_length=10)),
                ('administrado', models.BooleanField()),
                ('costo', models.DecimalField(decimal_places=2, max_digits=18)),
            ],
        ),
        migrations.CreateModel(
            name='Paramedicos',
            fields=[
                ('clave', models.IntegerField(primary_key=1, serialize=False)),
                ('nombre', models.TextField(max_length=100)),
                ('usuario', models.TextField(max_length=10)),
                ('contrasena', models.TextField(max_length=10)),
                ('mando', models.TextField(max_length=1)),
                ('conocimiento', models.TextField(max_length=1)),
                ('tipo', models.TextField(max_length=1)),
                ('estatus', models.TextField(max_length=1)),
                ('observacion', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Procedimiento',
            fields=[
                ('clave', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
                ('protocolo', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='TipoUnidad',
            fields=[
                ('clave', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Calle_Colonia',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('calle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.calle')),
                ('colonia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.colonia')),
            ],
        ),
        migrations.CreateModel(
            name='Enfermedad',
            fields=[
                ('clave', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=70)),
                ('engrafica', models.CharField(max_length=1)),
                ('grupoenfermedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.grupoenfermedad')),
            ],
        ),
        migrations.CreateModel(
            name='TiposServicio',
            fields=[
                ('clave', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
                ('sobresaliente', models.CharField(max_length=1)),
                ('engrafica', models.CharField(max_length=1)),
                ('gruposervicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.gruposervicio')),
            ],
        ),
    ]
