# Generated by Django 5.1.7 on 2025-06-05 19:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alergia',
            fields=[
                ('clave', models.IntegerField(primary_key=1, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Bases',
            fields=[
                ('clave', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('estacion', models.CharField(max_length=50)),
                ('ubicacion', models.CharField(max_length=100)),
                ('color_hex', models.CharField(help_text='Código de color en formato hexadecimal (ej. #FF5733)', max_length=7, validators=[django.core.validators.RegexValidator(message='El color debe estar en formato hexadecimal, por ejemplo: #FF5733', regex='^#([A-Fa-f0-9]{6})$')])),
            ],
        ),
        migrations.CreateModel(
            name='Calle',
            fields=[
                ('clave', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('calle', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Colonia',
            fields=[
                ('clave', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('colonia', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('clave', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
                ('unidad', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='GrupoEnfermedad',
            fields=[
                ('clave', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='GrupoServicio',
            fields=[
                ('clave', models.IntegerField(primary_key=1, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Hospitales',
            fields=[
                ('clave', models.IntegerField(primary_key=1, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('ubicacion', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='MarcaVehiculo',
            fields=[
                ('clave', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('clave', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
                ('unidad', models.CharField(max_length=10)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=18, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('clave', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
                ('unidad', models.CharField(max_length=10)),
                ('administrado', models.BooleanField()),
                ('costo', models.DecimalField(decimal_places=2, max_digits=18, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Paramedicos',
            fields=[
                ('clave', models.IntegerField(primary_key=1, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('usuario', models.CharField(max_length=10)),
                ('contrasena', models.CharField(max_length=10)),
                ('mando', models.CharField(max_length=1)),
                ('conocimiento', models.CharField(max_length=1)),
                ('tipo', models.CharField(max_length=1)),
                ('estatus', models.CharField(max_length=1)),
                ('observacion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Procedimiento',
            fields=[
                ('clave', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
                ('protocolo', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='TipoUnidad',
            fields=[
                ('clave', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ambulancias',
            fields=[
                ('clave', models.CharField(max_length=5, primary_key=1, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=1)),
                ('base', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.bases')),
            ],
        ),
        migrations.CreateModel(
            name='Calle_Colonia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('calle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.calle')),
                ('colonia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.colonia')),
            ],
        ),
        migrations.CreateModel(
            name='Enfermedad',
            fields=[
                ('clave', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=70)),
                ('engrafica', models.CharField(max_length=1)),
                ('grupoenfermedad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.grupoenfermedad')),
            ],
        ),
        migrations.CreateModel(
            name='TiposServicio',
            fields=[
                ('clave', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
                ('sobresaliente', models.CharField(max_length=1, null=True)),
                ('engrafica', models.CharField(max_length=1, null=True)),
                ('gruposervicio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.gruposervicio')),
            ],
        ),
    ]
