# Generated by Django 5.1.7 on 2025-06-05 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calle',
            name='clave',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='colonia',
            name='clave',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
