# Generated by Django 5.1.7 on 2025-03-28 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calle',
            name='id',
        ),
        migrations.RemoveField(
            model_name='colonia',
            name='id',
        ),
        migrations.AddField(
            model_name='calle',
            name='clave',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='colonia',
            name='clave',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
