# Generated by Django 5.1.7 on 2025-06-05 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0002_alter_calle_clave_alter_colonia_clave'),
    ]

    operations = [
        migrations.AddField(
            model_name='calle_colonia',
            name='calle_txt',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calle_colonia',
            name='colonia_txt',
            field=models.CharField(default='X', max_length=300),
            preserve_default=False,
        ),
    ]
