# Generated by Django 5.1.7 on 2025-03-31 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0002_remove_calle_id_remove_colonia_id_calle_clave_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alergia',
            name='descripcion',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='ambulancias',
            name='base',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='ambulancias',
            name='clave',
            field=models.CharField(max_length=5, primary_key=1, serialize=False),
        ),
        migrations.AlterField(
            model_name='ambulancias',
            name='descripcion',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='ambulancias',
            name='estado',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='bases',
            name='clave',
            field=models.CharField(max_length=20, primary_key=1, serialize=False),
        ),
        migrations.AlterField(
            model_name='bases',
            name='estacion',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='bases',
            name='ubicacion',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='paramedicos',
            name='conocimiento',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='paramedicos',
            name='contrasena',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='paramedicos',
            name='estatus',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='paramedicos',
            name='mando',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='paramedicos',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='paramedicos',
            name='observacion',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='paramedicos',
            name='tipo',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='paramedicos',
            name='usuario',
            field=models.CharField(max_length=10),
        ),
    ]
