# Generated by Django 5.1.7 on 2025-04-16 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0003_alter_alergia_descripcion_alter_ambulancias_base_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calle_colonia',
            name='calle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.calle'),
        ),
        migrations.AlterField(
            model_name='calle_colonia',
            name='colonia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.colonia'),
        ),
        migrations.AlterField(
            model_name='enfermedad',
            name='grupoenfermedad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.grupoenfermedad'),
        ),
        migrations.AlterField(
            model_name='tiposservicio',
            name='gruposervicio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.gruposervicio'),
        ),
    ]
