# Generated by Django 5.1.7 on 2025-06-05 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0003_calle_colonia_calle_txt_calle_colonia_colonia_txt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calle_colonia',
            name='calle_txt',
        ),
        migrations.RemoveField(
            model_name='calle_colonia',
            name='colonia_txt',
        ),
    ]
