# Generated by Django 5.1.7 on 2025-06-11 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0004_remove_calle_colonia_calle_txt_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logs_Sistema',
            fields=[
                ('clave', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.CharField(max_length=50)),
                ('accion', models.CharField(max_length=255)),
            ],
        ),
    ]
