# Generated by Django 5.1.7 on 2025-05-22 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0004_alter_calle_colonia_calle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colonia',
            name='clave',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
