# Generated by Django 5.1.7 on 2025-06-16 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0005_logs_sistema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paramedicos',
            name='contrasena',
            field=models.CharField(max_length=130),
        ),
    ]
