# Generated by Django 5.1.7 on 2025-05-22 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0005_alter_colonia_clave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calle',
            name='clave',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
