# Generated by Django 5.1.7 on 2025-08-07 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0006_alter_paramedicos_contrasena'),
    ]

    operations = [
        migrations.AddField(
            model_name='paramedicos',
            name='permisos',
            field=models.IntegerField(choices=[(1, 'Lectura'), (2, 'Lectura y escritura')], default=1),
        ),
    ]
