# Generated by Django 5.1.7 on 2025-05-23 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0006_alter_calle_clave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambulancias',
            name='base',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.bases'),
        ),
    ]
