# Generated by Django 5.1.7 on 2025-08-08 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0007_paramedicos_permisos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paramedicos',
            name='permisos',
            field=models.IntegerField(choices=[(1, 'Lectura'), (2, 'Lectura y escritura'), (3, 'Super Usuario')], default=1),
        ),
    ]
