# Generated by Django 5.1.7 on 2025-05-23 17:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0007_alter_ambulancias_base'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bases',
            name='azul',
        ),
        migrations.RemoveField(
            model_name='bases',
            name='rojo',
        ),
        migrations.RemoveField(
            model_name='bases',
            name='verde',
        ),
        migrations.AddField(
            model_name='bases',
            name='color_hex',
            field=models.CharField(default='#FFFFFF', help_text='Código de color en formato hexadecimal (ej. #FF5733)', max_length=7, validators=[django.core.validators.RegexValidator(message='El color debe estar en formato hexadecimal, por ejemplo: #FF5733', regex='^#([A-Fa-f0-9]{6})$')]),
            preserve_default=False,
        ),
    ]
