# Generated by Django 5.1.7 on 2025-08-08 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0008_alter_paramedicos_permisos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paramedicos',
            name='permisos',
            field=models.IntegerField(default=1),
        ),
    ]
