# Generated by Django 5.1.7 on 2025-05-23 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0008_remove_bases_azul_remove_bases_rojo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calle_colonia',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
