# Generated by Django 5.1.7 on 2025-06-04 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0009_alter_calle_colonia_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiposservicio',
            name='engrafica',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='tiposservicio',
            name='sobresaliente',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
