# Generated by Django 5.1.7 on 2025-06-04 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0011_alter_medicamento_costo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='costo',
            field=models.DecimalField(decimal_places=2, max_digits=18, null=True),
        ),
    ]
